# This file is a part of the UMSKT Project
#
# Copyleft (C) 2019-2024 UMSKT Contributors (et.al.)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# @FileCreated by TheTank20 on 06/13/2023
# @Maintainer Neo

name: C/C++ CI (Windows)

on:
  push:
    branches: [ "*" ]
    paths-ignore: [ '**.md', 'doc/**', '.idea/**'] # If only these files are edited, skip
  workflow_dispatch:

jobs:
  prepare:
    runs-on: windows-latest
    steps:
      # https://github.com/actions/runner-images/issues/6067#issuecomment-1213069040
      - name: Install Windows XP Support for Visual Studio
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          $componentsToAdd = @(
            "Microsoft.VisualStudio.Component.WinXP"
          )
          [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -eq 0)
          {
              Write-Host "components have been successfully added"
              Get-ChildItem C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.Windows.XPSupport.*
          }
          else
          {
              Write-Host "components were not installed"
              exit 1
          }

      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

  build:
    runs-on: windows-latest
    needs: prepare
    strategy:
      matrix:
        arch: [ { name: Win32, displayName: x86 }, { name: x64, displayName: x64} ]
    steps:
      - name: Configure and build UMSKT for ${{ matrix.values.displayName }}
        uses: threeal/cmake-action@v1.3.0
        with:
          options: CMAKE_BUILD_TYPE=Release
          generator: "Visual Studio 17 2022"
          args: -A "${{ matrix.arch.name }}" -T "v141_xp"
          run-build: true
          build-args: "--config Release"

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: UMSKT-${{ matrix.values.displayName }}
          path: build/Release
